# enum UserRole { SUPERADMIN, ADMIN, EDITOR, USER }
UserRole:
    type: enum
    config:
        description: "App defined User Roles"
        values:
            SUPERADMIN:
                value: 1
                description: "Top level Administrator"
                # to deprecate a value, only set the deprecation reason
                #deprecationReason: "Just because"
            ADMIN:
                value: 2
                description: "Admin with restricted privileges"
            EDITOR:
                value: 3
                description: "Admin with only basic privileges"            
            USER:
                value: 4
                description: "App User with privliges only to his account and his content"